# Base docker compose, added to by docker-compose.override or docker-compose.prod. See Readme.md

services:
  # PHP & apache container using offical Docker PHP iamge
  web:
    build: .
    links:
      - db
      - emoncms
    ports:
      # Expose heatpumpmonitor on localhost port 8080
      - 8080:80
    volumes:
      # Mount heatpumpmonitor files from local FS for dev
      - ./www:/var/www/heatpumpmonitororg
    working_dir: /var/www/heatpumpmonitororg
    env_file:
      - 'default.docker-env'
    depends_on:
      load_dev_env_data:
        condition: service_completed_successfully

  # This container will load the data (if requested) and then stop
  load_dev_env_data:
    build: .
    links:
      - db
    volumes:
      - ./www:/var/www/heatpumpmonitororg
      - ./dev_env/load_dev_env_data.php:/var/load_dev_env_data.php:ro
      - ./load_installer_logos.php:/var/load_installer_logos.php:ro
      - ./generate_thumbnails.php:/var/generate_thumbnails.php:ro
    working_dir: /var/www/heatpumpmonitororg
    env_file:
      - 'default.docker-env'
    environment:
      - "RELOAD_ALL=0"
      - "CLEAR_DB=0"
      - "LOAD_USERS=1"
      - "LOAD_SYSTEM_META=1"
      - "LOAD_RUNNING_STATS=1"
      - "LOAD_MONTHLY_STATS=0"
      - "LOAD_DAILY_STATS=0"
      - "LOAD_MANUFACTURERS=1"
      - "LOAD_HEATPUMP_MODELS=1"
    entrypoint: ["bash", "-c", "php /var/load_dev_env_data.php && php /var/generate_thumbnails.php "]
    depends_on:
      db:
        condition: service_healthy

  emoncms:
    image: ghcr.io/jeremypoulter/emoncms:pr-1
    ports:
      - 8081:80
    volumes:
      - emon-phpfina:/var/opt/emoncms/phpfina
      - emon-phptimeseries:/var/opt/emoncms/phptimeseries
    links:
      - db
      - redis
      - mqtt
    env_file:
      - 'emoncms.docker-env'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:11.0
    environment:
      - "MYSQL_HOST=localhost"
      - "MARIADB_AUTO_UPGRADE=1"
      - "MARIADB_INITDB_SKIP_TZINFO=1"
    env_file:
      - 'default.docker-env'
    volumes:
      - emon-db-data:/var/lib/mysql
      - ./docker/emoncms-init.sql:/docker-entrypoint-initdb.d/02-emoncms.sql:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - 3306:3306
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 1s
      start_period: 60s
      timeout: 2s
      retries: 10

  redis:
    image: redis:7.0
    volumes:
      - emon-redis-data:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"

  mqtt:
    image: eclipse-mosquitto:2.0
    build: docker/mqtt
    ports:
      - 1883:1883
    logging:
      driver: json-file
      options:
        max-size: "10m"

volumes:
  emon-db-data:
    driver: local
  emon-phpfina:
    driver: local
  emon-phptimeseries:
    driver: local
  emon-redis-data:
    driver: local
